---
- name: Install Docker on Ubuntu 24.04 and test without sudo
  hosts: all
  become: true
  vars:
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
    docker_compose_version: "2.24.6"
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
    
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
        state: present
    
    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes
    
    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
    
    - name: Create docker group if it doesn't exist
      group:
        name: docker
        state: present
    
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Reset ssh connection to apply group changes
      meta: reset_connection
    
    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-{{ docker_apt_arch }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    
    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false
      become: false
    
    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: compose_version
      changed_when: false
      become: false
    
    - name: Display Docker version
      debug:
        var: docker_version.stdout
    
    - name: Display Docker Compose version
      debug:
        var: compose_version.stdout
    
    - name: Test Docker installation without sudo
      command: docker run hello-world
      register: hello_world
      changed_when: false
      become: false
    
    - name: Display Docker test result
      debug:
        var: hello_world.stdout_lines